apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "storj-storagenode.fullname" . }}
  labels:
    {{- include "storj-storagenode.labels" . | nindent 4 }}
data:
  WALLET: {{ required "Don't forget your ERC20 wallet" .Values.configWallet }}
  EMAIL: {{ required "Must provide an email address" .Values.configEmail }}
  ADDRESS: {{ required "The address to connect your node" .Values.configAddress }}
  BANDWIDTH: {{ .Values.configBandwidth }}
  STORAGE: {{ .Values.configStorage }}
