apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "storj-storagenode.fullname" . }}
  labels:
    {{- include "storj-storagenode.labels" . | nindent 4 }}
data:
{{ (.Files.Glob .Values.identityPath).AsSecrets | indent 2 }}
