{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "storj-storagenode.serviceAccountName" . }}
  labels:
{{ include "storj-storagenode.labels" . | nindent 4 }}
{{- end -}}
