apiVersion: v1
kind: Service
metadata:
  name: {{ include "storj-storagenode.fullname" . }}
  labels:
    {{- include "storj-storagenode.labels" . | nindent 4 }}
spec:
  {{- with .Values.service }}
  type: {{ .type }}
  ports:
    - port: {{ .storagenode.port }}
      targetPort: storagenode
      protocol: TCP
      name: storagenode
      {{ if .storagenode.nodePort }}nodePort: {{ .storagenode.nodePort }}{{ end }}
  {{- end }}
    {{- if .Values.nodeStats.enabled }}
    {{- with .Values.service.stats }}
    - port: {{ .port }}
      targetPort: stats
      protocol: TCP
      name: stats
      {{ if .nodePort }}nodePort: {{ .nodePort }}{{ end }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "storj-storagenode.selectorLabels" . | nindent 4 }}
