apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "storj-storagenode.fullname" . }}
  labels:
    {{- include "storj-storagenode.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "storj-storagenode.fullname" . }}
  selector:
    matchLabels:
      {{- include "storj-storagenode.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "storj-storagenode.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "storj-storagenode.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: storj
              containerPort: 9151
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: storj
          readinessProbe:
            tcpSocket:
              port: storj
          envFrom:
            - configMapRef:
                name: {{ include "storj-storagenode.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence }}
            - name: {{ include "storj-storagenode.fullname" . }}
              mountPath: /app/config
            {{- end }}
            - name: storj-identity
              mountPath: /app/identity
      volumes:
        - name: storj-identity
          secret:
            secretName: {{ include "storj-storagenode.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: {{ include "storj-storagenode.fullname" . }}
    {{- with .Values.persistence.annotations  }}
      annotations:
{{ toYaml . | indent 8 }}
    {{- end }}
    spec:
{{ toYaml .Values.volumeClaimTemplate | indent 6 }}
  {{- end }}
