apiVersion: v1
kind: Service
metadata:
  name: {{ include "storj-storagenode.fullname" . }}
  labels:
    {{- include "storj-storagenode.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  {{- with .Values.service }}
  type: {{ .type }}
  {{ if .loadBalancerIP }}loadBalancerIP: {{ .loadBalancerIP }}{{ end }}
  ports:
    - port: {{ .port }}
      targetPort: storagenode
      protocol: TCP
      name: storagenode
      {{ if .nodePort }}nodePort: {{ .nodePort }}{{ end }}
  {{- end }}
  selector:
    {{- include "storj-storagenode.selectorLabels" . | nindent 4 }}
---
{{- if .Values.nodeStats.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "storj-storagenode.fullname" . }}-stats
  labels:
    {{- include "storj-storagenode.labels" . | nindent 4 }}
spec:
  {{- with .Values.nodeStats.service }}
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      targetPort: stats
      protocol: TCP
      name: stats
      {{ if .nodePort }}nodePort: {{ .nodePort }}{{ end }}
  {{- end }}
  selector:
    {{- include "storj-storagenode.selectorLabels" . | nindent 4 }}
{{- end }}
